services:
  db:
    image: postgres:16-alpine
    container_name: todo_postgres
    restart: no
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todo_user -d todo" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_grails
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Para application.yml do Grails
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=todo
      - DB_USER=todo_user
      - DB_PASSWORD=todo_password
    volumes:
      - ./backend:/app
      - gradle_cache:/root/.gradle

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo_angular
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

volumes:
  pgdata:
  gradle_cache:
  node_modules: